### ISSUE TITLE
Unknown Prop Warning

### ISSUE THREAD

**Issue by goldmont** [react-cropper/react-cropper#1071]
Hi,

In the latest release, Cropper's props are passed down to the HTML element and thus React complains about it. The error is the following:

> Warning: React does not recognize the `aspectRatio` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `aspectratio` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

This error is logged for every prop I set. Could you please solve it? Thanks.

**Comment by jcolombo** [comment]
Yup same here... props are all getting sent on to the DOM with one of the spreads or something instead of scrubbing out the unneeded props. Not sure we thats in this package or the Cropper.js itself but I definitely can't build to production with all those console errors. If it matters i am running React in Typescript and the Material UI library.

**Comment by shekhar-shubhendu** [comment]
Thanks for raising this. I will look into it

**Comment by goldmont** [comment]
Thanks.

**Comment by shekhar-shubhendu** [comment]
@goldmont @jcolombo Please try the latest version. It should be fixed there.
