### ISSUE TITLE
Does work with signed urls

### ISSUE THREAD

**Issue by developdeez** [react-cropper/react-cropper#119]
Tried with Amazon signedURLs got errors.

**Comment by john-aws** [comment]
@developdeez This issue should be titled "Does **not** work with signed URLs". Please correct.

The problem is that this library, or some dependency, appends a `timestamp=<epochtime>` query parameter to the `src` URL when attempting to retrieve the image, and the introduction of this parameter breaks AWS signing validation.

Additionally, it seems that the image GET attempt triggers CORS errors, even though a regular GET of the pre-signed URL from the same page works fine, as follows:

> No 'Access-Control-Allow-Origin' header is present on the requested resource.

This requires you to add a CORS configuration to the S3 bucket, along the lines of:

```
<CORSConfiguration>
   <CORSRule>
       <AllowedOrigin>https://my-website.s3.amazonaws.com</AllowedOrigin>
       <AllowedMethod>GET</AllowedMethod>
       <AllowedHeader>*</AllowedHeader>
       <MaxAgeSeconds>3000</MaxAgeSeconds>
       <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
       <ExposeHeader>x-amz-request-id</ExposeHeader>
       <ExposeHeader>x-amz-id-2</ExposeHeader>
   </CORSRule>
</CORSConfiguration>
```

It would be good to understand why this is, because I don't think it should be necessary when loading a web page from the same, origin domain.

**Comment by john-aws** [comment]
Believe that the solution here is to suppress the cache-busting timestamp query parameter in [cropperjs](https://github.com/fengyuanchen/cropperjs) via `checkCrossOrigin`, as follows:

`<ReactCrop src={imgurl} style={style} crop={crop} checkCrossOrigin={false} />`

**Comment by skeptic007** [comment]
I am still facing issues with aws presigned url images. am i missing something?
